1、ctrl+?,选中批量注释脚本，再ctrl+? 取消注释  
2、tab,选中批量向后缩进（2个空格）,shift+tab 向前进  
3、option,alt 齐列选中（进行删除编辑等操作）  

In [2]:
import math

In [3]:
math.pi

3.141592653589793

In [4]:
math.e

2.718281828459045

In [5]:
math.log(10)

2.302585092994046

In [6]:
abs(-2)

2

In [7]:
def threenumadd(x,y,z):
    numsum=x+y+z
    return numsum

In [8]:
a=threenumadd(10,20,30)

In [9]:
a

60

In [10]:
def add():
    x=10+20
    return x

In [11]:
b=add()
b

30

In [12]:
import pandas as pd

In [13]:
a=[1,2,3]
type(a),a

(list, [1, 2, 3])

In [14]:
a=(1,2,3)
type(a),a

(tuple, (1, 2, 3))

In [15]:
a={'a':"zhangsan",'b':'xiaoming'}
type(a),a

(dict, {'a': 'zhangsan', 'b': 'xiaoming'})

In [16]:
a['a']

'zhangsan'

In [17]:
a.keys()

dict_keys(['a', 'b'])

In [18]:
a.values()

dict_values(['zhangsan', 'xiaoming'])

In [19]:
for k,v in a.items():
    print(k,v)

a zhangsan
b xiaoming


In [20]:
b=range(0,10)
type(b)

range

In [21]:
for i in b:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
c=[j for j in b] #生成器

In [23]:
type(c),c

(list, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
def sum2(x):
    return x*2

In [25]:
[i for i in map(sum2,c)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
lambda s: s*2 #匿名函数

<function __main__.<lambda>(s)>

In [27]:
[i for i in map(lambda s:s*3,c)]

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [28]:
from functools import reduce

In [29]:
reduce(lambda a,b:a+b,c)

45

In [30]:
filter(lambda s:s>5,c)

In [31]:
[i for i in filter(lambda s:s>5,c)]

[6, 7, 8, 9]

In [32]:
import pandas as pd

In [33]:
df=pd.read_csv('forestfires.csv')

In [34]:
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [35]:
type(df)

pandas.core.frame.DataFrame

In [36]:
df.to_csv('forestfires_tocsv.csv',index=False) #index=False不导出索引

In [37]:
df['X']

0      7
1      7
2      7
3      8
4      8
      ..
512    4
513    2
514    7
515    1
516    6
Name: X, Length: 517, dtype: int64

In [38]:
type(df['X'])

pandas.core.series.Series

In [39]:
df[['X','Y']]#取多列

X  Y
0    7  5
1    7  4
2    7  4
3    8  6
4    8  6
..  .. ..
512  4  3
513  2  4
514  7  4
515  1  4
516  6  3

[517 rows x 2 columns]

In [40]:
df.loc[2] #取行,loc是针对索引的名称来取值，如若索引是非数字，不能取值

X            7
Y            4
month      oct
day        sat
FFMC      90.6
DMC       43.7
DC       686.9
ISI        6.7
temp      14.6
RH          33
wind       1.3
rain         0
area         0
Name: 2, dtype: object

In [41]:
df.loc[0:4] #取指定行(按索引）

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [42]:
df[:5] #取前5行，按行号（前闭后开）

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [43]:
df[:5][['X','Y']]#取多行多列

X  Y
0  7  5
1  7  4
2  7  4
3  8  6
4  8  6

In [44]:
??df.rename  #?或？？打开帮助

Object `df.rename  #?或？？打开帮助` not found.


In [45]:
df.rename(columns={'X':'x',"Y":"y"}) #更改产生新的df,需要重新赋值给df

x  y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [46]:
df.rename(columns={'X':'x',"Y":"y"},inplace=True) #inplace=True，更改df直接生效，不需要重新赋值

In [47]:
df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [48]:
df1=df.drop_duplicates() #删除重复值

In [49]:
df.shape

(517, 13)

In [50]:
df1.shape

(513, 13)

In [51]:
df1=df.drop_duplicates(subset=['month','day']) #针对某几列去重

In [52]:
df['month'].value_counts() #按列计算频次，相当于count groupby

aug    184
sep    172
mar     54
jul     32
feb     20
jun     17
oct     15
dec      9
apr      9
may      2
jan      2
nov      1
Name: month, dtype: int64

In [53]:
df['xx']=df['x']+df['x'] #增加新列xx

In [54]:
df['xx']

0      14
1      14
2      14
3      16
4      16
       ..
512     8
513     4
514    14
515     2
516    12
Name: xx, Length: 517, dtype: int64

In [55]:
df.describe()  #将df的基本计算输出

x           y        FFMC         DMC          DC         ISI  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     4.669246    4.299807   90.644681  110.872340  547.940039    9.021663   
std      2.313778    1.229900    5.520111   64.046482  248.066192    4.559477   
min      1.000000    2.000000   18.700000    1.100000    7.900000    0.000000   
25%      3.000000    4.000000   90.200000   68.600000  437.700000    6.500000   
50%      4.000000    4.000000   91.600000  108.300000  664.200000    8.400000   
75%      7.000000    5.000000   92.900000  142.400000  713.900000   10.800000   
max      9.000000    9.000000   96.200000  291.300000  860.600000   56.100000   

             temp          RH        wind        rain         area          xx  
count  517.000000  517.000000  517.000000  517.000000   517.000000  517.000000  
mean    18.889168   44.288201    4.017602    0.021663    12.847292    9.338491  
std      5.806625   16.317469    1.791653    0.295959    63.655818    4.627556  
min      2.200000   15.000000    0.400000    0.000000     0.000000    2.000000  
25%     15.500000   33.000000    2.700000    0.000000     0.000000    6.000000  
50%     19.300000   42.000000    4.000000    0.000000     0.520000    8.000000  
75%     22.800000   53.000000    4.900000    0.000000     6.570000   14.000000  
max     33.300000  100.000000    9.400000    6.400000  1090.840000   18.000000

In [56]:
df[0:5]

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16

# 索引切片

In [95]:
df.iloc[:5] #和上面df[:5]的效果一样，iloc作用在索引位或列位置选取，不能按名筛选

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16   

  Lable Label label  
0   NaN     L     S  
1   NaN     L     S  
2   NaN     L     S  
3   NaN     L     S  
4   NaN     L     S

In [96]:
df.iloc[:5,[2,3]] #取0：5行，2-3列，多行多列按位置筛选，无法按名字筛选

month  day
0   mar  fri
1   oct  tue
2   oct  sat
3   mar  fri
4   mar  sun

In [57]:
df.loc[0:5]#loc是按索引名和列名来筛选

x  y month  day  FFMC   DMC     DC   ISI  temp  RH  wind  rain  area  xx
0  7  5   mar  fri  86.2  26.2   94.3   5.1   8.2  51   6.7   0.0   0.0  14
1  7  4   oct  tue  90.6  35.4  669.1   6.7  18.0  33   0.9   0.0   0.0  14
2  7  4   oct  sat  90.6  43.7  686.9   6.7  14.6  33   1.3   0.0   0.0  14
3  8  6   mar  fri  91.7  33.3   77.5   9.0   8.3  97   4.0   0.2   0.0  16
4  8  6   mar  sun  89.3  51.3  102.2   9.6  11.4  99   1.8   0.0   0.0  16
5  8  6   aug  sun  92.3  85.3  488.0  14.7  22.2  29   5.4   0.0   0.0  16

In [124]:
dfnewday=df.set_index('day')#索引设置为day
dfnewday.head()

x  y month  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx Lable  \
day                                                                             
fri  7  5   mar  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14   NaN   
tue  7  4   oct  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14   NaN   
sat  7  4   oct  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14   NaN   
fri  8  6   mar  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16   NaN   
sun  8  6   mar  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16   NaN   

    Label label  
day              
fri     L     S  
tue     L     S  
sat     L     S  
fri     L     S  
sun     L     S

In [123]:
dfday=dfnewday.reset_index('day')#将索引逆转设置为列,与上一句相反的作用
dfday.head()

day  x  y month  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  fri  7  5   mar  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14   
1  tue  7  4   oct  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14   
2  sat  7  4   oct  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14   
3  fri  8  6   mar  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16   
4  sun  8  6   mar  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16   

  Lable Label label  
0   NaN     L     S  
1   NaN     L     S  
2   NaN     L     S  
3   NaN     L     S  
4   NaN     L     S

In [61]:
dfnew=df.set_index('month') #改变，设置索引

In [122]:
dfnew.head()

x  y  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx
month                                                                   
mar    7  5  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14
oct    7  4  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14
oct    7  4  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14
mar    8  6  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16
mar    8  6  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16

In [65]:
dfnew.loc['mar'].head() #按索引名或列名来筛选，无法按位置筛选，和iloc相反

x  y  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx
month                                                                   
mar    7  5  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14
mar    8  6  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16
mar    8  6  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16
mar    5  5  sat  91.7  35.8   80.8  7.8  15.1  27   5.4   0.0   0.0  10
mar    6  4  wed  89.2  27.9   70.8  6.3  15.9  35   4.0   0.0   0.0  12

In [66]:
dfnew.loc[['mar','aug']]#用列表选择多个索引名或多个列名

x  y  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  xx
month                                                                      
mar    7  5  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00  14
mar    8  6  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00  16
mar    8  6  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00  16
mar    5  5  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   0.0   0.00  10
mar    6  4  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   0.0   0.00  12
...   .. ..  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...  ..
aug    8  6  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00  16
aug    4  3  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44   8
aug    2  4  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   4
aug    7  4  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16  14
aug    1  4  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00   2

[238 rows x 13 columns]

In [84]:
df.loc[0:4,['month','day','area']]#loc可以同时取行和列，用逗号隔开，多项选择用列表

month  day  area
0   mar  fri   0.0
1   oct  tue   0.0
2   oct  sat   0.0
3   mar  fri   0.0
4   mar  sun   0.0

In [89]:
df.loc[df['area']>=6.57,'label']='L' #loc可以过滤出True的结果
df.loc[(df['area']<6.57 )& (df['area']>=0.52),'label']='M'
df.loc[df['area']<0.52,'label']='S'

In [86]:
df.loc[df['label']=='L']

x  y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  \
183  7  4   oct  mon  91.7   48.5  696.1  11.1  16.8  45   4.5   0.0   6.83   
184  8  6   aug  fri  93.9  135.7  586.7  15.1  20.8  34   4.9   0.0   6.96   
185  2  5   sep  tue  91.0  129.5  692.6   7.0  17.6  46   3.1   0.0   7.04   
186  8  6   mar  sun  89.3   51.3  102.2   9.6  11.5  39   5.8   0.0   7.19   
187  1  5   sep  mon  90.9  126.5  686.5   7.0  21.0  42   2.2   0.0   7.30   
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...   
498  6  5   aug  tue  96.1  181.1  671.2  14.3  33.3  26   2.7   0.0  40.54   
499  7  5   aug  tue  96.1  181.1  671.2  14.3  27.3  63   4.9   6.4  10.82   
504  4  3   aug  wed  94.5  139.4  689.1  20.0  28.9  29   4.9   0.0  49.59   
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16   

     xx Lable Label label  
183  14     L     L     L  
184  16     L     L     L  
185   4     L     L     L  
186  16     L     L     L  
187   2     L     L     L  
..   ..   ...   ...   ...  
498  12     L     L     L  
499  14     L     L     L  
504   8     L     L     L  
513   4     L     L     L  
514  14     L     L     L  

[130 rows x 17 columns]

In [94]:
df['label'].value_counts()#计数

S    257
M    130
L    130
Name: label, dtype: int64

In [93]:
df['label'].value_counts().sum()#计数后汇总

517

In [115]:
df.query("month=='mar' & day=='tue'")#查找

x  y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain  area  xx  \
39   4  4   mar  tue  88.1  25.7  67.6   3.8  14.1  43   2.7   0.0   0.0   8   
114  3  4   mar  tue  88.1  25.7  67.6   3.8  15.8  27   7.6   0.0   0.0   6   
115  3  5   mar  tue  88.1  25.7  67.6   3.8  15.5  27   6.3   0.0   0.0   6   
134  3  5   mar  tue  88.1  25.7  67.6   3.8  14.9  38   2.7   0.0   0.0   6   
393  2  4   mar  tue  93.4  15.0  25.6  11.4  15.2  19   7.6   0.0   0.0   4   

    Lable Label label  
39    NaN     L     S  
114   NaN     L     S  
115   NaN     L     S  
134   NaN     L     S  
393   NaN     L     S

# 多重索引切片

In [127]:
df1=df.set_index(['month','day'],drop=False) #设置多重索引,drop=False代表列仍然保留
df1.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  \
month day                                                                  
mar   fri  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   
oct   tue  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   
      sat  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   
mar   fri  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   
      sun  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   

           area  xx Lable Label label  
month day                              
mar   fri   0.0  14   NaN     L     S  
oct   tue   0.0  14   NaN     L     S  
      sat   0.0  14   NaN     L     S  
mar   fri   0.0  16   NaN     L     S  
      sun   0.0  16   NaN     L     S

In [129]:
df1.sort_index(inplace=True) #sort_index排序，inplace=True改变并替换原df,不用再定义新的df
df1

x  y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  \
month day                                                                    
apr   fri  4  4   apr  fri  83.0   23.3   85.3   2.3  16.7  20   3.1   0.0   
      mon  6  5   apr  mon  87.9   24.9   41.6   3.7  10.9  64   3.1   0.0   
      sat  6  4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   0.0   
      sun  7  5   apr  sun  81.9    3.0    7.9   3.5  13.4  75   1.8   0.0   
      sun  6  3   apr  sun  91.0   14.6   25.6  12.3  13.7  33   9.4   0.0   
...       .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...   
sep   wed  6  5   sep  wed  92.6  115.4  777.1   8.8  24.3  27   4.9   0.0   
      wed  4  4   sep  wed  92.6  115.4  777.1   8.8  19.7  41   1.8   0.0   
      wed  3  4   sep  wed  91.2  134.7  817.5   7.2  18.5  30   2.7   0.0   
      wed  2  4   sep  wed  87.9   84.8  725.1   3.7  21.8  34   2.2   0.0   
      wed  7  4   sep  wed  89.7  284.9  844.0  10.1  10.5  77   4.0   0.0   

            area  xx Lable Label label  
month day                               
apr   fri   0.00   8   NaN     L     S  
      mon   3.35  12   NaN     L     M  
      sat   0.00  12   NaN     L     S  
      sun   0.00  14   NaN     L     S  
      sun  61.13  12     L     L     L  
...          ...  ..   ...   ...   ...  
sep   wed   0.00  12   NaN     L     S  
      wed   1.58   8   NaN     L     M  
      wed   0.00   6   NaN     L     S  
      wed   6.04   4   NaN     L     M  
      wed   0.00  14   NaN     L     S  

[517 rows x 17 columns]

In [131]:
df1.loc[('mar','fri'),['x','y']]  #筛选出，索引名为mar,fri，列名为x，y的

x  y
month day      
mar   fri  7  5
      fri  8  6
      fri  4  5
      fri  4  5
      fri  5  4
      fri  8  6
      fri  4  5
      fri  4  4
      fri  3  4
      fri  6  5
      fri  6  5

In [134]:
df1.loc[(['mar','oct'],['fri','tue']),['x','y']] 
#筛选出，索引一是mar/oct,索引二为fri/tue，列名为x，y的

x  y
month day      
mar   fri  7  5
      fri  8  6
      fri  4  5
      fri  4  5
      fri  5  4
      fri  8  6
      fri  4  5
      fri  4  4
      fri  3  4
      fri  6  5
      fri  6  5
      tue  4  4
      tue  3  4
      tue  3  5
      tue  3  5
      tue  2  4
oct   fri  7  4
      tue  7  4
      tue  6  3

In [145]:
df1.loc[('mar','fri'),['x','y']] #多重索引筛选

x  y
day      
fri  7  5
fri  8  6
fri  4  5
fri  4  5
fri  5  4
fri  8  6
fri  4  5
fri  4  4
fri  3  4
fri  6  5
fri  6  5
mon  4  4
mon  4  4
mon  1  3
mon  3  4
mon  3  5
mon  4  6
mon  5  4
mon  7  4
mon  7  3
mon  6  5
mon  4  3
mon  6  5
sat  5  5
sat  6  5
sat  3  4
sat  3  4
sat  3  4
sat  6  3
sat  6  4
sat  5  6
sat  4  4
sat  4  4
sun  8  6
sun  2  2
sun  2  2
sun  4  6
sun  8  6
sun  7  4
sun  6  5
thu  4  5
thu  6  5
thu  6  5
thu  5  5
thu  6  5
tue  4  4
tue  3  4
tue  3  5
tue  3  5
tue  2  4
wed  6  4
wed  6  5
wed  3  4
wed  3  4

In [139]:
df1.loc[(slice=(None),['fri','tue']),['x','y']] 

SyntaxError: invalid syntax (<ipython-input-139-055bdc4f5f1e>, line 1)

# 分组

In [147]:
df.columns #查看列

Index(['x', 'y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH',
       'wind', 'rain', 'area', 'xx', 'Lable', 'Label', 'label'],
      dtype='object')

In [148]:
df.index #查看索引

RangeIndex(start=0, stop=517, step=1)

In [149]:
 df.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx  \
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14   
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14   
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14   
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16   
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16   

  Lable Label label  
0   NaN     L     S  
1   NaN     L     S  
2   NaN     L     S  
3   NaN     L     S  
4   NaN     L     S

In [152]:
grouped=df.groupby(['month','day'])
grouped  #DataFrameGroupBy

In [161]:
len(grouped) #64个group小组

64

In [162]:
grouped.size()

month  day
apr    fri     1
       mon     1
       sat     1
       sun     3
       thu     2
              ..
sep    sat    25
       sun    27
       thu    21
       tue    19
       wed    14
Length: 64, dtype: int64

In [163]:
grouped.sum()#分组sum计算，只针对数字列计算

x    y    FFMC     DMC       DC    ISI   temp    RH   wind  rain  \
month day                                                                       
apr   fri    4    4    83.0    23.3     85.3    2.3   16.7    20    3.1   0.0   
      mon    6    5    87.9    24.9     41.6    3.7   10.9    64    3.1   0.0   
      sat    6    4    86.3    27.4     97.1    5.1    9.3    44    4.5   0.0   
      sun   18   12   263.9    32.2     59.1   28.1   44.7   135   17.0   0.0   
      thu   12   10   163.0    18.2    110.4    5.4   11.6   108   11.6   0.0   
...        ...  ...     ...     ...      ...    ...    ...   ...    ...   ...   
sep   sat  115  108  2301.8  2903.7  18237.0  214.9  538.1   946   86.5   0.0   
      sun   98  107  2431.7  3608.8  19880.6  205.0  551.8  1296  106.8   0.0   
      thu   90   86  1939.8  2554.7  15527.4  200.1  428.2   638   70.5   0.0   
      tue   89   79  1710.7  2146.8  13644.6  129.7  355.7   831   65.2   0.0   
      wed   63   63  1283.1  1735.5  10338.2  119.1  285.7   530   47.3   0.0   

              area   xx  
month day                
apr   fri     0.00    8  
      mon     3.35   12  
      sat     0.00   12  
      sun    61.13   36  
      thu    15.54   24  
...            ...  ...  
sep   sat  1545.11  230  
      sun   378.29  196  
      thu   112.48  180  
      tue   500.69  178  
      wed   182.40  126  

[64 rows x 12 columns]

In [164]:
grouped.count()

x   y  FFMC  DMC  DC  ISI  temp  RH  wind  rain  area  xx  Lable  \
month day                                                                      
apr   fri   1   1     1    1   1    1     1   1     1     1     1   1      0   
      mon   1   1     1    1   1    1     1   1     1     1     1   1      0   
      sat   1   1     1    1   1    1     1   1     1     1     1   1      0   
      sun   3   3     3    3   3    3     3   3     3     3     3   3      1   
      thu   2   2     2    2   2    2     2   2     2     2     2   2      1   
...        ..  ..   ...  ...  ..  ...   ...  ..   ...   ...   ...  ..    ...   
sep   sat  25  25    25   25  25   25    25  25    25    25    25  25      8   
      sun  27  27    27   27  27   27    27  27    27    27    27  27      8   
      thu  21  21    21   21  21   21    21  21    21    21    21  21      5   
      tue  19  19    19   19  19   19    19  19    19    19    19  19      8   
      wed  14  14    14   14  14   14    14  14    14    14    14  14      4   

           Label  label  
month day                
apr   fri      1      1  
      mon      1      1  
      sat      1      1  
      sun      3      3  
      thu      2      2  
...          ...    ...  
sep   sat     25     25  
      sun     27     27  
      thu     21     21  
      tue     19     19  
      wed     14     14  

[64 rows x 15 columns]

In [165]:
grouped.mean()

x         y       FFMC         DMC          DC       ISI  \
month day                                                                    
apr   fri  4.000000  4.000000  83.000000   23.300000   85.300000  2.300000   
      mon  6.000000  5.000000  87.900000   24.900000   41.600000  3.700000   
      sat  6.000000  4.000000  86.300000   27.400000   97.100000  5.100000   
      sun  6.000000  4.000000  87.966667   10.733333   19.700000  9.366667   
      thu  6.000000  5.000000  81.500000    9.100000   55.200000  2.700000   
...             ...       ...        ...         ...         ...       ...   
sep   sat  4.600000  4.320000  92.072000  116.148000  729.480000  8.596000   
      sun  3.629630  3.962963  90.062963  133.659259  736.318519  7.592593   
      thu  4.285714  4.095238  92.371429  121.652381  739.400000  9.528571   
      tue  4.684211  4.157895  90.036842  112.989474  718.136842  6.826316   
      wed  4.500000  4.500000  91.650000  123.964286  738.442857  8.507143   

                temp         RH      wind  rain       area         xx  
month day                                                              
apr   fri  16.700000  20.000000  3.100000   0.0   0.000000   8.000000  
      mon  10.900000  64.000000  3.100000   0.0   3.350000  12.000000  
      sat   9.300000  44.000000  4.500000   0.0   0.000000  12.000000  
      sun  14.900000  45.000000  5.666667   0.0  20.376667  12.000000  
      thu   5.800000  54.000000  5.800000   0.0   7.770000  12.000000  
...              ...        ...       ...   ...        ...        ...  
sep   sat  21.524000  37.840000  3.460000   0.0  61.804400   9.200000  
      sun  20.437037  48.000000  3.955556   0.0  14.010741   7.259259  
      thu  20.390476  30.380952  3.357143   0.0   5.356190   8.571429  
      tue  18.721053  43.736842  3.431579   0.0  26.352105   9.368421  
      wed  20.407143  37.857143  3.378571   0.0  13.028571   9.000000  

[64 rows x 12 columns]

In [166]:
grouped[['x','y']].median() #中位数

x    y
month day          
apr   fri  4.0  4.0
      mon  6.0  5.0
      sat  6.0  4.0
      sun  6.0  4.0
      thu  6.0  5.0
...        ...  ...
sep   sat  5.0  5.0
      sun  3.0  4.0
      thu  4.0  4.0
      tue  4.0  4.0
      wed  4.0  4.0

[64 rows x 2 columns]

In [168]:
import numpy as np

In [174]:
grouped['x','y'].aggregate([np.sum,np.mean,np.median])
#求多个计算值

d:\software\python\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


x                     y                 
           sum      mean median  sum      mean median
month day                                            
apr   fri    4  4.000000    4.0    4  4.000000    4.0
      mon    6  6.000000    6.0    5  5.000000    5.0
      sat    6  6.000000    6.0    4  4.000000    4.0
      sun   18  6.000000    6.0   12  4.000000    4.0
      thu   12  6.000000    6.0   10  5.000000    5.0
...        ...       ...    ...  ...       ...    ...
sep   sat  115  4.600000    5.0  108  4.320000    5.0
      sun   98  3.629630    3.0  107  3.962963    4.0
      thu   90  4.285714    4.0   86  4.095238    4.0
      tue   89  4.684211    4.0   79  4.157895    4.0
      wed   63  4.500000    4.0   63  4.500000    4.0

[64 rows x 6 columns]

In [176]:
#agg针对不同的列，不同的计算公式
grouped.agg({'DMC':np.sum,'DC':np.mean,'ISI':np.median})

DMC          DC   ISI
month day                          
apr   fri    23.3   85.300000   2.3
      mon    24.9   41.600000   3.7
      sat    27.4   97.100000   5.1
      sun    32.2   19.700000  12.3
      thu    18.2   55.200000   2.7
...           ...         ...   ...
sep   sat  2903.7  729.480000   8.4
      sun  3608.8  736.318519   8.1
      thu  2554.7  739.400000   8.6
      tue  2146.8  718.136842   7.0
      wed  1735.5  738.442857   9.0

[64 rows x 3 columns]

In [178]:
for name,group in grouped:
    print(name)

('apr', 'fri')
('apr', 'mon')
('apr', 'sat')
('apr', 'sun')
('apr', 'thu')
('apr', 'wed')
('aug', 'fri')
('aug', 'mon')
('aug', 'sat')
('aug', 'sun')
('aug', 'thu')
('aug', 'tue')
('aug', 'wed')
('dec', 'fri')
('dec', 'mon')
('dec', 'sun')
('dec', 'thu')
('dec', 'tue')
('dec', 'wed')
('feb', 'fri')
('feb', 'mon')
('feb', 'sat')
('feb', 'sun')
('feb', 'thu')
('feb', 'tue')
('feb', 'wed')
('jan', 'sat')
('jan', 'sun')
('jul', 'fri')
('jul', 'mon')
('jul', 'sat')
('jul', 'sun')
('jul', 'thu')
('jul', 'tue')
('jul', 'wed')
('jun', 'fri')
('jun', 'mon')
('jun', 'sat')
('jun', 'sun')
('jun', 'thu')
('jun', 'wed')
('mar', 'fri')
('mar', 'mon')
('mar', 'sat')
('mar', 'sun')
('mar', 'thu')
('mar', 'tue')
('mar', 'wed')
('may', 'fri')
('may', 'sat')
('nov', 'tue')
('oct', 'fri')
('oct', 'mon')
('oct', 'sat')
('oct', 'sun')
('oct', 'tue')
('oct', 'wed')
('sep', 'fri')
('sep', 'mon')
('sep', 'sat')
('sep', 'sun')
('sep', 'thu')
('sep', 'tue')
('sep', 'wed')


In [182]:
for name,group in grouped:
    print(group.head())
    print(type(group))

     x  y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
241  4  4   apr  fri  83.0  23.3  85.3  2.3  16.7  20   3.1   0.0   0.0   8   

    Lable Label label  
241   NaN     L     S  
<class 'pandas.core.frame.DataFrame'>
     x  y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
442  6  5   apr  mon  87.9  24.9  41.6  3.7  10.9  64   3.1   0.0  3.35  12   

    Lable Label label  
442   NaN     L     M  
<class 'pandas.core.frame.DataFrame'>
    x  y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
19  6  4   apr  sat  86.3  27.4  97.1  5.1   9.3  44   4.5   0.0   0.0  12   

   Lable Label label  
19   NaN     L     S  
<class 'pandas.core.frame.DataFrame'>
     x  y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain   area  xx  \
239  7  5   apr  sun  81.9   3.0   7.9   3.5  13.4  75   1.8   0.0   0.00  14   
469  6  3   apr  sun  91.0  14.6  25.6  12.3  13.7  33   9.4   0.0  61.13  12   
470  5  4   apr  sun  91.0

     x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain   area  xx  \
182  5  4   feb  sun  86.8  15.6   48.3  3.9  12.4  53   2.2   0.0   6.38  10   
202  7  4   feb  sun  83.9   8.7   32.1  2.1   8.8  68   2.2   0.0  13.05  14   
282  6  3   feb  sun  84.9  27.5  353.5  3.4   4.2  51   4.0   0.0   0.00  12   
395  4  5   feb  sun  85.0   9.0   56.9  3.5  10.1  62   1.8   0.0  51.78   8   

    Lable Label label  
182   NaN     L     M  
202     L     L     L  
282   NaN     L     S  
395     L     L     L  
<class 'pandas.core.frame.DataFrame'>
    x  y month  day  FFMC  DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
75  9  9   feb  thu  84.2  6.8  26.6  7.7   6.7  79   3.1   0.0   0.0  18   

   Lable Label label  
75   NaN     L     S  
<class 'pandas.core.frame.DataFrame'>
     x  y month  day  FFMC  DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
463  6  5   feb  tue  75.1  4.4  16.2  1.9   4.6  82   6.3   0.0  5.39  12   
464  6  4   feb  tue  75.1  4.4  16.2  1.

     x  y month  day  FFMC   DMC    DC   ISI  temp  RH  wind  rain  area  xx  \
39   4  4   mar  tue  88.1  25.7  67.6   3.8  14.1  43   2.7   0.0   0.0   8   
114  3  4   mar  tue  88.1  25.7  67.6   3.8  15.8  27   7.6   0.0   0.0   6   
115  3  5   mar  tue  88.1  25.7  67.6   3.8  15.5  27   6.3   0.0   0.0   6   
134  3  5   mar  tue  88.1  25.7  67.6   3.8  14.9  38   2.7   0.0   0.0   6   
393  2  4   mar  tue  93.4  15.0  25.6  11.4  15.2  19   7.6   0.0   0.0   4   

    Lable Label label  
39    NaN     L     S  
114   NaN     L     S  
115   NaN     L     S  
134   NaN     L     S  
393   NaN     L     S  
<class 'pandas.core.frame.DataFrame'>
     x  y month  day  FFMC   DMC    DC  ISI  temp  RH  wind  rain  area  xx  \
18   6  4   mar  wed  89.2  27.9  70.8  6.3  15.9  35   4.0   0.0  0.00  12   
417  6  5   mar  wed  93.4  17.3  28.3  9.9  13.8  24   5.8   0.0  0.00  12   
447  3  4   mar  wed  93.4  17.3  28.3  9.9   8.9  35   8.0   0.0  0.00   6   
467  3  4   mar  wed 

178   4   NaN     L     M  
<class 'pandas.core.frame.DataFrame'>


In [191]:
df1=df.set_index(['month','day'])
df1.head()

x  y  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  xx Lable  \
month day                                                                       
mar   fri  7  5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0  14   NaN   
oct   tue  7  4  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0  14   NaN   
      sat  7  4  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0  14   NaN   
mar   fri  8  6  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0  16   NaN   
      sun  8  6  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0  16   NaN   

          Label label  
month day              
mar   fri     L     S  
oct   tue     L     S  
      sat     L     S  
mar   fri     L     S  
      sun     L     S

In [193]:
df1=df.set_index(['month','day'],drop=False) #drop=False保留列
df1.head()

x  y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  \
month day                                                                  
mar   fri  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   
oct   tue  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   
      sat  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   
mar   fri  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   
      sun  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   

           area  xx Lable Label label  
month day                              
mar   fri   0.0  14   NaN     L     S  
oct   tue   0.0  14   NaN     L     S  
      sat   0.0  14   NaN     L     S  
mar   fri   0.0  16   NaN     L     S  
      sun   0.0  16   NaN     L     S

In [194]:
#删除列'month','day',axis=1代表列操作
df1.drop(['month','day'],axis=1,inplace=True)
df1

x  y  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  xx  \
month day                                                                    
mar   fri  7  5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00  14   
oct   tue  7  4  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00  14   
      sat  7  4  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00  14   
mar   fri  8  6  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00  16   
      sun  8  6  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00  16   
...       .. ..   ...    ...    ...   ...   ...  ..   ...   ...    ...  ..   
aug   sun  4  3  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44   8   
      sun  2  4  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29   4   
      sun  7  4  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16  14   
      sat  1  4  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00   2   
nov   tue  6  3  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00  12   

          Lable Label label  
month day                    
mar   fri   NaN     L     S  
oct   tue   NaN     L     S  
      sat   NaN     L     S  
mar   fri   NaN     L     S  
      sun   NaN     L     S  
...         ...   ...   ...  
aug   sun   NaN     L     M  
      sun     L     L     L  
      sun     L     L     L  
      sat   NaN     L     S  
nov   tue   NaN     L     S  

[517 rows x 15 columns]

In [198]:
groupedindex=df1.groupby(['month','day'])
groupedindex

In [199]:
groupedindex.sum()

x    y    FFMC     DMC       DC    ISI   temp    RH   wind  rain  \
month day                                                                       
apr   fri    4    4    83.0    23.3     85.3    2.3   16.7    20    3.1   0.0   
      mon    6    5    87.9    24.9     41.6    3.7   10.9    64    3.1   0.0   
      sat    6    4    86.3    27.4     97.1    5.1    9.3    44    4.5   0.0   
      sun   18   12   263.9    32.2     59.1   28.1   44.7   135   17.0   0.0   
      thu   12   10   163.0    18.2    110.4    5.4   11.6   108   11.6   0.0   
...        ...  ...     ...     ...      ...    ...    ...   ...    ...   ...   
sep   sat  115  108  2301.8  2903.7  18237.0  214.9  538.1   946   86.5   0.0   
      sun   98  107  2431.7  3608.8  19880.6  205.0  551.8  1296  106.8   0.0   
      thu   90   86  1939.8  2554.7  15527.4  200.1  428.2   638   70.5   0.0   
      tue   89   79  1710.7  2146.8  13644.6  129.7  355.7   831   65.2   0.0   
      wed   63   63  1283.1  1735.5  10338.2  119.1  285.7   530   47.3   0.0   

              area   xx  
month day                
apr   fri     0.00    8  
      mon     3.35   12  
      sat     0.00   12  
      sun    61.13   36  
      thu    15.54   24  
...            ...  ...  
sep   sat  1545.11  230  
      sun   378.29  196  
      thu   112.48  180  
      tue   500.69  178  
      wed   182.40  126  

[64 rows x 12 columns]

# 多表操作concat;merge

# enumerate

In [200]:
alist=['a','b','c']

In [201]:
list(enumerate(alist))#enumerate找出索引位置

[(0, 'a'), (1, 'b'), (2, 'c')]

In [202]:
list(enumerate(df1.columns)) #可以打印出df的所有列的索引位置

[(0, 'x'),
 (1, 'y'),
 (2, 'FFMC'),
 (3, 'DMC'),
 (4, 'DC'),
 (5, 'ISI'),
 (6, 'temp'),
 (7, 'RH'),
 (8, 'wind'),
 (9, 'rain'),
 (10, 'area'),
 (11, 'xx'),
 (12, 'Lable'),
 (13, 'Label'),
 (14, 'label')]

In [207]:
bdir={}
for i in enumerate(df.columns):
    bdir[i[1]]=i[0]  #索引与列转置成一个字典，找到列的位置数
print(bdir)

{'x': 0, 'y': 1, 'month': 2, 'day': 3, 'FFMC': 4, 'DMC': 5, 'DC': 6, 'ISI': 7, 'temp': 8, 'RH': 9, 'wind': 10, 'rain': 11, 'area': 12, 'xx': 13, 'Lable': 14, 'Label': 15, 'label': 16}


In [208]:
bdir['label'] #找到label列的位置

16

In [209]:
df.iloc[:5,16]

0    S
1    S
2    S
3    S
4    S
Name: label, dtype: object

In [215]:
#透视表
pd.pivot_table(df,index='y',columns='x',values='FFMC',aggfunc=np.mean)

x          1          2          3          4          5          6  \
y                                                                     
2  91.968421  91.132000        NaN        NaN        NaN        NaN   
3  92.060000  91.600000  92.200000  91.445455        NaN  90.444000   
4  91.506667  89.188889  90.611628  90.866667  91.852174  89.311111   
5  92.200000  92.240000  90.414286  88.332000  92.200000  89.012245   
6        NaN        NaN  91.375000  85.700000  91.850000  95.466667   
8        NaN        NaN        NaN        NaN        NaN        NaN   
9        NaN        NaN        NaN        NaN        NaN        NaN   

x          7          8          9  
y                                   
2        NaN        NaN        NaN  
3  89.100000  88.766667        NaN  
4  90.891111  91.600000  89.700000  
5  91.600000  90.200000  93.300000  
6  92.150000  91.451923  91.600000  
8        NaN  91.700000        NaN  
9        NaN        NaN  89.116667

In [217]:
#交叉表,相当于excel里面的
pd.crosstab(df['month'],df['day'],margins=True)

day    fri  mon  sat  sun  thu  tue  wed  All
month                                        
apr      1    1    1    3    2    0    1    9
aug     21   15   29   40   26   28   25  184
dec      1    4    0    1    1    1    1    9
feb      5    3    4    4    1    2    1   20
jan      0    0    1    1    0    0    0    2
jul      3    4    8    5    3    6    3   32
jun      3    3    2    4    2    0    3   17
mar     11   12   10    7    5    5    4   54
may      1    0    1    0    0    0    0    2
nov      0    0    0    0    0    1    0    1
oct      1    4    3    3    0    2    2   15
sep     38   28   25   27   21   19   14  172
All     85   74   84   95   61   64   54  517

# Numpy学习

In [218]:
import numpy as np

In [220]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [221]:
a.ndim #查看数组维度

2

In [223]:
np.array(df) #df转化为array,python底层都是array格式

array([[7, 5, 'mar', ..., nan, 'L', 'S'],
       [7, 4, 'oct', ..., nan, 'L', 'S'],
       [7, 4, 'oct', ..., nan, 'L', 'S'],
       ...,
       [7, 4, 'aug', ..., 'L', 'L', 'L'],
       [1, 4, 'aug', ..., nan, 'L', 'S'],
       [6, 3, 'nov', ..., nan, 'L', 'S']], dtype=object)

In [224]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
np.arange(1,10,2) #2是步长

array([1, 3, 5, 7, 9])

In [228]:
np.linspace(1,11,num=10) #等分切割，等差数列

array([ 1.        ,  2.11111111,  3.22222222,  4.33333333,  5.44444444,
        6.55555556,  7.66666667,  8.77777778,  9.88888889, 11.        ])

In [229]:
np.linspace(1,10,num=10) #等分切割，等差数列

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [230]:
np.ones((10,10)) #构建shape: 10行10列

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [233]:
np.random.rand(100)

array([9.21721954e-01, 8.47226110e-01, 4.23496053e-01, 3.20181535e-01,
       1.81184857e-01, 8.45794182e-01, 8.44268028e-02, 6.46630539e-01,
       3.59020856e-01, 3.06189647e-01, 4.97962789e-01, 5.11435622e-01,
       7.85385521e-02, 7.47368286e-01, 5.22647175e-01, 1.73898298e-03,
       8.76633070e-02, 5.16018500e-01, 1.91782691e-02, 4.62515336e-02,
       1.02323335e-01, 5.18373829e-01, 6.42358002e-01, 5.73424768e-01,
       6.81871459e-01, 4.60621780e-01, 7.20483039e-01, 1.15557721e-01,
       6.21659219e-01, 8.69011834e-01, 3.15141391e-01, 7.62187680e-01,
       7.85036198e-01, 3.54343254e-01, 9.77663966e-01, 4.39372505e-02,
       3.03421467e-02, 9.64507889e-01, 6.29144556e-01, 6.45090255e-01,
       2.33018895e-01, 2.67308366e-01, 4.02964482e-01, 3.33214028e-02,
       8.39115552e-01, 7.95929970e-02, 2.52447527e-01, 1.21714910e-01,
       2.01894969e-01, 3.07948608e-01, 3.91713237e-01, 7.83655851e-01,
       2.59917877e-04, 7.72289231e-01, 4.59680550e-01, 9.80452092e-01,
      

In [235]:
np.random.randint(100,size=[3,4]) #size就是shape

array([[15, 88, 89, 54],
       [15,  8, 66, 28],
       [63,  2, 33,  4]])

In [237]:
np.random.randn(100) #符合正态分布

array([ 0.68462312, -0.75767861,  0.24904988,  1.00851888,  0.99022686,
        1.94554225,  0.88506591,  0.36720603, -0.94135893, -1.28163192,
        1.98833836, -2.58724493,  0.28828181,  1.67700632, -0.10961382,
        0.65378086, -0.44850677,  1.86940166,  0.4549773 ,  1.53789756,
        0.93996309,  0.44046896,  1.15806586, -1.27398898,  1.8459344 ,
        0.00281424,  0.5768349 , -0.27639752,  1.43816273, -0.07520628,
       -2.26154373, -1.25525663, -1.13483764,  0.0606457 , -0.34058452,
       -0.74236176,  0.10118807,  0.93799627, -0.86033139, -0.47185011,
       -0.36949527,  0.83780509,  0.12778802,  1.26834938, -1.78341623,
        0.81974245,  0.92295699, -1.33368091,  0.40003387, -1.30969794,
       -0.46654953,  1.14767526, -1.22830792, -0.89819886, -2.52566795,
        0.33530505,  1.6730869 ,  0.06209576,  1.66358609,  0.20177235,
        0.77124477, -0.14367444,  1.7464954 ,  0.15651756,  0.59736299,
       -0.23372996, -2.57278813, -1.11737611,  0.96260102,  0.63

In [239]:
np.random.random(10) #返回10个 0~1之间的浮点数

array([0.74890578, 0.569572  , 0.68457905, 0.06478395, 0.82249917,
       0.05158111, 0.91846517, 0.694114  , 0.3956424 , 0.87296594])

In [240]:
len(np.random.random(10))

10

In [245]:
a= np.random.randint(10,size=(3,4))
b= np.random.randint(10,size=(3,4))
a,b

(array([[3, 8, 3, 2],
        [8, 3, 4, 6],
        [3, 8, 6, 5]]),
 array([[6, 7, 7, 1],
        [9, 6, 5, 7],
        [7, 0, 1, 7]]))

In [243]:
np.concatenate((a,b),axis=0)

array([[5, 2, 1, 1],
       [6, 1, 4, 3],
       [2, 5, 4, 5],
       [4, 0, 0, 3],
       [0, 7, 0, 8],
       [4, 6, 6, 3]])

In [247]:
np.sum(a)

59

In [248]:
np.sum(a,axis=1)

array([16, 21, 22])

In [ ]:
pd.set_option('display.max_columns', None) #显示所有行